### PR TITLE
Update for 2.2.2 release *(macOS)*

### PR DESCRIPTION
**Pull request by Martii**
Presuming this is wanted again.

Release is at [/Martii/qupzilla/releases/tag/v2.2.2+81bb81c](https://github.com/Martii/qupzilla/releases/tag/v2.2.2%2B81bb51c)

Prerequisite:
* Upload to qupzilla.com

### CODE REVIEW

**Comment by Martii** [comment]
Should be noted that the QupZilla icon on the .dmg didn't show up when mounted... but Apple has been slinging many updates for the last few days. Didn't think that would be blocking. The updates I have installed seems to have fixed QupZilla/qupzilla#2517 ... time shall tell.

**Comment by Martii** [comment]
Hang on a bit... I'm going to regenerate this... weird bug... found a work around...

**Comment by Martii** [comment]
Okay... rereleased with [QupZilla/qupzilla#2524](https://github.com/QupZilla/qupzilla/pull/2524). New sha256 included in the release doc. ❤️ Linux way better!

**Comment by Martii** [comment]
Btw it appears my A/V is the culprit for freezing up the bookmarks toolbar in High Sierra... happens completely randomly as well as predictably after a compile when I turn it back on. Guess I'll just run with it off until needed.

**Comment by nowrep** [comment]
Thanks

**Pull request merged**
